### ISSUE TITLE
docker pull: error response

### ISSUE THREAD

**Issue by michaelsmolka** [sethforprivacy/sparrow-server-docker#35]
root@srv-file:~# docker pull ghcr.io/sethforprivacy/sparrow-server-docker: latest Clipboard support in Python scripts Error response from daemon: Head "https://ghcr.io/v2/sethforprivacy/sparrow-server-docker/manifests/latest": denied

**Comment by sethforprivacy** [comment]
Odd, just tested on multiple hosts with no issues.

Could you share more about your setup? The package is public and downloadable without creds.

**Comment by michaelsmolka** [comment]
my technical understanding is not deep enough to really help with this.
My initial intention was to install this on my Synology NAS. Got help from a guy in a forum. He discoverd this and posted above error message.
Finally I got it up and running using this image, what I guess is the same as the one on Github: https://registry.hub.docker.com/r/sethsimmons/sparrow-server/

P.S.: But I guess since yesterday, we can cancel this topic anyways, as there is no usecase for Sparrow terminal anymore.
